import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';

export default [
  js.configs.recommended,
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'test-api.js',
      '*.config.js',
      '*.config.mjs'
    ],
  },
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        ReadableStream: 'readonly',
        AbortController: 'readonly',
        performance: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        self: 'readonly',
        importScripts: 'readonly',
        WebAssembly: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        DocumentFragment: 'readonly',
        ShadowRoot: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        NodeFilter: 'readonly',
        HTMLInputElement: 'readonly',
        CSS: 'readonly',
        DOMRect: 'readonly',
        getComputedStyle: 'readonly',
        matchMedia: 'readonly',
        devicePixelRatio: 'readonly',
        reportError: 'readonly',
        queueMicrotask: 'readonly',
        setImmediate: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        __REACT_DEVTOOLS_GLOBAL_HOOK__: 'readonly',
        __webpack_nonce__: 'readonly',
        TURBOPACK_NEXT_CHUNK_URLS: 'readonly',
        TURBOPACK_WORKER_LOCATION: 'readonly'
      }
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'off', // Turn off since we're providing globals
      'no-empty': 'warn',
      'no-fallthrough': 'warn',
      'no-cond-assign': 'warn',
      'no-case-declarations': 'warn',
      'no-redeclare': 'warn',
      'no-prototype-builtins': 'warn',
      'no-misleading-character-class': 'warn',
      'no-control-regex': 'warn',
      'valid-typeof': 'warn',
      'getter-return': 'warn'
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsparser,
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        ReadableStream: 'readonly',
        AbortController: 'readonly',
        performance: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        self: 'readonly',
        importScripts: 'readonly',
        WebAssembly: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        DocumentFragment: 'readonly',
        ShadowRoot: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        NodeFilter: 'readonly',
        HTMLInputElement: 'readonly',
        CSS: 'readonly',
        DOMRect: 'readonly',
        getComputedStyle: 'readonly',
        matchMedia: 'readonly',
        devicePixelRatio: 'readonly',
        reportError: 'readonly',
        queueMicrotask: 'readonly',
        setImmediate: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        __REACT_DEVTOOLS_GLOBAL_HOOK__: 'readonly',
        __webpack_nonce__: 'readonly',
        TURBOPACK_NEXT_CHUNK_URLS: 'readonly',
        TURBOPACK_WORKER_LOCATION: 'readonly'
      }
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-undef': 'off',
      'no-empty': 'warn',
      'no-fallthrough': 'warn',
      'no-cond-assign': 'warn',
      'no-case-declarations': 'warn',
      'no-redeclare': 'warn',
      'no-prototype-builtins': 'warn',
      'no-misleading-character-class': 'warn',
      'no-control-regex': 'warn',
      'valid-typeof': 'warn',
      'getter-return': 'warn'
    },
  },
];
